#!/bin/bash
# Quick Start Guide - Print when user opens project

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   🚀 MICROSERVICE PLATFORM - QUICK START GUIDE 🚀             ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 WHAT'S READY:"
echo "  ✅ Complete Docker Compose with 20 services"
echo "  ✅ Angular 21 Frontend (Tailwind CSS)"
echo "  ✅ Keycloak Identity Provider"
echo "  ✅ 6 Spring Boot Service Templates"
echo "  ✅ PostgreSQL (per-service databases)"
echo "  ✅ Kafka + Redis"
echo "  ✅ MinIO Object Storage"
echo "  ✅ Jenkins CI/CD"
echo "  ✅ Prometheus + Grafana Monitoring"
echo ""
echo "🚀 QUICK START:"
echo ""
echo "  1️⃣  Copy environment file:"
echo "     cp .env.example .env"
echo ""
echo "  2️⃣  Start all services (Linux/macOS):"
echo "     docker-compose up -d"
echo ""
echo "  2️⃣  Start all services (Windows PowerShell):"
echo "     .\dev.ps1 start"
echo ""
echo "  3️⃣  Wait 2-3 minutes for services to start"
echo ""
echo "  4️⃣  Verify all services running:"
echo "     docker-compose ps"
echo ""
echo "🌐 ACCESS SERVICES:"
echo ""
echo "  Frontend:        http://localhost:8080"
echo "  Gateway API:     http://localhost:8000/swagger-ui"
echo "  Keycloak:        http://localhost:8180/admin"
echo "                   (admin / admin123)"
echo "  MinIO:           http://localhost:9001"
echo "                   (minioadmin / minioadmin)"
echo "  Jenkins:         http://localhost:8088"
echo "                   (admin / admin123)"
echo "  Grafana:         http://localhost:3000"
echo "                   (admin / admin123)"
echo "  Prometheus:      http://localhost:9090"
echo ""
echo "📚 DOCUMENTATION:"
echo ""
echo "  README.md           - Complete guide"
echo "  QUICK_REFERENCE.md  - Common commands"
echo "  ARCHITECTURE.md     - Service dependencies"
echo "  CHECKLIST.md        - Implementation plan"
echo "  SETUP_COMPLETE.md   - What's been setup"
echo ""
echo "💡 HELPFUL COMMANDS:"
echo ""
echo "  View logs:"
echo "    docker-compose logs -f [service-name]"
echo ""
echo "  Stop services:"
echo "    docker-compose down"
echo ""
echo "  Reset (delete all data):"
echo "    docker-compose down -v"
echo ""
echo "  Rebuild specific service:"
echo "    docker-compose up -d --build [service-name]"
echo ""
echo "🛠️  NEXT STEPS:"
echo ""
echo "  1. Review ARCHITECTURE.md for service dependencies"
echo "  2. Check QUICK_REFERENCE.md for useful commands"
echo "  3. Read README.md for detailed setup instructions"
echo "  4. Start with 'docker-compose up -d'"
echo "  5. Monitor services via Grafana (localhost:3000)"
echo ""
echo "⚠️  SYSTEM REQUIREMENTS:"
echo ""
echo "  • Docker & Docker Compose 2.0+"
echo "  • 8GB+ RAM"
echo "  • 5GB+ disk space"
echo "  • Node.js 22+ (for Angular development)"
echo "  • Java 17+ (for Spring Boot development)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Happy coding! 🎉"
echo ""
