package huynv.eventinfra.util;

import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class TraceHeaderUtilTest {

  private static final String VALID_TRACE_ID = "4bf92f3577b34da6a3ce929d0e0e4736";

  /**
   * Verifies that {@link TraceHeaderUtil#putTraceHeaders} adds both a {@code traceparent}
   * header and a {@code traceId} header when a valid 32-character hex trace ID is provided.
   *
   * @return void — asserts that traceparent and traceId headers are present and correctly set.
   */
  @Test
  void putTraceHeaders_validTraceId_addsTraceparentAndTraceIdHeaders() {
    Map<String, String> headers = new HashMap<>();
    TraceHeaderUtil.putTraceHeaders(headers, VALID_TRACE_ID, "corr-001", "span-seed");
    assertThat(headers).containsKey("traceparent");
    assertThat(headers).containsKey("traceId");
    assertThat(headers.get("traceId")).isEqualTo(VALID_TRACE_ID);
  }

  /**
   * Verifies that the {@code traceparent} header generated by {@link TraceHeaderUtil#putTraceHeaders}
   * conforms to the W3C Trace Context format: {@code 00-<32hexTraceId>-<16hexSpanId>-01}.
   *
   * @return void — asserts that the traceparent value matches the W3C format regex.
   */
  @Test
  void putTraceHeaders_traceparentFollowsW3cFormat() {
    Map<String, String> headers = new HashMap<>();
    TraceHeaderUtil.putTraceHeaders(headers, VALID_TRACE_ID, null, "seed");
    String traceparent = headers.get("traceparent");
    assertThat(traceparent).matches("00-[0-9a-f]{32}-[0-9a-f]{16}-01");
  }

  /**
   * Verifies that no headers are added to the map when the trace ID is {@code null},
   * preventing malformed trace context from being propagated to Kafka consumers.
   *
   * @return void — asserts that the headers map remains empty when trace ID is null.
   */
  @Test
  void putTraceHeaders_nullTraceId_noHeadersAdded() {
    Map<String, String> headers = new HashMap<>();
    TraceHeaderUtil.putTraceHeaders(headers, null, "corr", "seed");
    assertThat(headers).isEmpty();
  }

  /**
   * Verifies that no headers are added to the map when the trace ID is a blank string,
   * treating whitespace-only values as absent to prevent invalid trace context propagation.
   *
   * @return void — asserts that the headers map remains empty when trace ID is blank.
   */
  @Test
  void putTraceHeaders_blankTraceId_noHeadersAdded() {
    Map<String, String> headers = new HashMap<>();
    TraceHeaderUtil.putTraceHeaders(headers, "   ", "corr", "seed");
    assertThat(headers).isEmpty();
  }

  /**
   * Verifies that when an optional {@code tracestate} vendor string is provided,
   * {@link TraceHeaderUtil#putTraceHeaders} includes it as the {@code tracestate} header.
   *
   * @return void — asserts that the tracestate header equals the supplied vendor string.
   */
  @Test
  void putTraceHeaders_withTracestate_addsTracestateHeader() {
    Map<String, String> headers = new HashMap<>();
    TraceHeaderUtil.putTraceHeaders(headers, VALID_TRACE_ID, "corr", "seed", "vendor=value");
    assertThat(headers.get("tracestate")).isEqualTo("vendor=value");
  }

  /**
   * Verifies that {@link TraceHeaderUtil#toTraceparent} returns {@code null} when the supplied
   * trace ID is not a valid 32-character lowercase hex string or is {@code null}, preventing
   * malformed W3C traceparent values from being propagated.
   *
   * @return void — asserts that invalid and null trace IDs both produce a null traceparent.
   */
  @Test
  void toTraceparent_invalidTraceId_returnsNull() {
    assertThat(TraceHeaderUtil.toTraceparent("not-hex", "seed")).isNull();
    assertThat(TraceHeaderUtil.toTraceparent(null, "seed")).isNull();
  }

  /**
   * Verifies that {@link TraceHeaderUtil#toTraceparent} produces the same output for
   * identical trace ID and span seed inputs, confirming deterministic span ID derivation.
   *
   * @return void — asserts that two calls with the same inputs produce equal traceparent strings.
   */
  @Test
  void toTraceparent_validTraceId_deterministic() {
    String result1 = TraceHeaderUtil.toTraceparent(VALID_TRACE_ID, "fixed-seed");
    String result2 = TraceHeaderUtil.toTraceparent(VALID_TRACE_ID, "fixed-seed");
    assertThat(result1).isEqualTo(result2);
  }
}
