package huynv.paymentservice.domain;

import huynv.paymentservice.exception.IllegalPaymentStateTransitionException;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.UUID;

/**
 * Payment aggregate that enforces payment state machine transitions and idempotency invariants.
 */
@Entity
@Table(
        name = "payments",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_payments_idempotency_key", columnNames = {"idempotency_key"})
        }
)
public class Payment {

    @Id
    @Column(name = "payment_id", nullable = false, updatable = false)
    private UUID paymentId;

    @Column(name = "order_id", nullable = false, updatable = false)
    private UUID orderId;

    @Column(name = "tenant_id")
    private Long tenantId;

    @Column(name = "amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal amount;

    @Column(name = "currency", nullable = false, length = 3)
    private String currency;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private PaymentStatus status;

    @Column(name = "provider", nullable = false, length = 64)
    private String provider;

    @Column(name = "transaction_id", length = 128)
    private String transactionId;

    @Column(name = "idempotency_key", nullable = false, length = 128, updatable = false)
    private String idempotencyKey;

    @Column(name = "correlation_id", length = 128)
    private String correlationId;

    @Column(name = "trace_id", length = 64)
    private String traceId;

    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    @Version
    @Column(name = "version", nullable = false)
    private long version;

    /**
     * Creates an empty JPA entity required by Hibernate.
     *
     * @return Initializes an empty payment entity instance.
     */
    protected Payment() {
    }

    /**
     * Creates a new payment aggregate in PENDING status.
     *
     * @param paymentId Payment identifier generated by the service.
     * @param orderId Order identifier associated with the payment.
     * @param tenantId Tenant identifier for multi-tenant correlation when available.
     * @param amount Amount to charge as an immutable monetary value.
     * @param currency ISO currency code for the amount.
     * @param provider Payment provider identifier used for charging.
     * @param idempotencyKey Idempotency key used to prevent duplicate charges.
     * @param correlationId Correlation identifier used to trace the saga across services.
     * @param traceId Trace identifier used to correlate distributed traces.
     * @param now Current timestamp used for audit fields.
     * @return Initializes a new payment aggregate in PENDING status.
     */
    public static Payment createPending(
            UUID paymentId,
            UUID orderId,
            Long tenantId,
            BigDecimal amount,
            String currency,
            String provider,
            String idempotencyKey,
            String correlationId,
            String traceId,
            OffsetDateTime now
    ) {
        Payment payment = new Payment();
        payment.paymentId = Objects.requireNonNull(paymentId, "paymentId");
        payment.orderId = Objects.requireNonNull(orderId, "orderId");
        payment.tenantId = tenantId;
        payment.amount = Objects.requireNonNull(amount, "amount");
        payment.currency = requireNonBlank(currency, "currency");
        payment.provider = requireNonBlank(provider, "provider");
        payment.idempotencyKey = requireNonBlank(idempotencyKey, "idempotencyKey");
        payment.correlationId = correlationId;
        payment.traceId = traceId;
        payment.status = PaymentStatus.PENDING;
        payment.createdAt = Objects.requireNonNull(now, "now");
        payment.updatedAt = now;
        return payment;
    }

    /**
     * Transitions payment from PENDING to PROCESSING for provider interaction.
     *
     * @param now Timestamp used to update audit fields.
     * @return Updates state to PROCESSING when transition is valid.
     */
    public void markProcessing(OffsetDateTime now) {
        enforceTransition(PaymentStatus.PENDING, PaymentStatus.PROCESSING);
        this.updatedAt = Objects.requireNonNull(now, "now");
    }

    /**
     * Marks payment as SUCCEEDED from PROCESSING and sets provider transaction identifier.
     *
     * @param transactionId Provider transaction identifier for traceability.
     * @param now Timestamp used to update audit fields.
     * @return Updates state to SUCCEEDED and stores the transaction id.
     */
    public void markSucceeded(String transactionId, OffsetDateTime now) {
        enforceTransition(PaymentStatus.PROCESSING, PaymentStatus.SUCCEEDED);
        this.transactionId = requireNonBlank(transactionId, "transactionId");
        this.updatedAt = Objects.requireNonNull(now, "now");
    }

    /**
     * Marks payment as FAILED from PROCESSING after provider error.
     *
     * @param now Timestamp used to update audit fields.
     * @return Updates state to FAILED when transition is valid.
     */
    public void markFailed(OffsetDateTime now) {
        enforceTransition(PaymentStatus.PROCESSING, PaymentStatus.FAILED);
        this.updatedAt = Objects.requireNonNull(now, "now");
    }

    /**
     * Cancels a payment that has not yet completed successfully.
     *
     * @param now Timestamp used to update audit fields.
     * @return Updates state to CANCELLED when transition is valid.
     */
    public void cancel(OffsetDateTime now) {
        enforceTransition(PaymentStatus.PENDING, PaymentStatus.CANCELLED);
        this.updatedAt = Objects.requireNonNull(now, "now");
    }

    /**
     * Returns the payment identifier.
     *
     * @return Payment identifier.
     */
    public UUID getPaymentId() {
        return paymentId;
    }

    /**
     * Returns the order identifier associated with this payment.
     *
     * @return Order identifier.
     */
    public UUID getOrderId() {
        return orderId;
    }

    /**
     * Returns the tenant identifier associated with this payment when available.
     *
     * @return Tenant identifier or null when not set.
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * Returns the amount charged for this payment.
     *
     * @return Monetary amount for the payment.
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Returns the payment currency.
     *
     * @return ISO currency code.
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Returns the current payment status.
     *
     * @return Current lifecycle status for the payment.
     */
    public PaymentStatus getStatus() {
        return status;
    }

    /**
     * Returns the provider name.
     *
     * @return Provider identifier for the payment.
     */
    public String getProvider() {
        return provider;
    }

    /**
     * Returns the provider transaction id when available.
     *
     * @return Provider transaction identifier or null when not set.
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Returns the idempotency key associated with the payment.
     *
     * @return Idempotency key.
     */
    public String getIdempotencyKey() {
        return idempotencyKey;
    }

    /**
     * Returns the correlation identifier associated with this payment when available.
     *
     * @return Correlation identifier or null when not set.
     */
    public String getCorrelationId() {
        return correlationId;
    }

    /**
     * Returns the trace identifier associated with this payment when available.
     *
     * @return Trace identifier or null when not set.
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * Returns the creation timestamp for the payment.
     *
     * @return Created timestamp.
     */
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns the last update timestamp for the payment.
     *
     * @return Updated timestamp.
     */
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Enforces a single expected-to-target state transition for the payment state machine.
     *
     * @param expected Expected current state for the transition.
     * @param target Target state after the transition.
     * @return Updates the payment status when the current state matches the expected state.
     */
    private void enforceTransition(PaymentStatus expected, PaymentStatus target) {
        if (this.status != expected) {
            throw new IllegalPaymentStateTransitionException(this.status, target);
        }
        this.status = target;
    }

    /**
     * Validates a string argument is non-null and non-blank.
     *
     * @param value Value to validate.
     * @param name Parameter name used in the exception message.
     * @return Returns the same value when it is non-blank.
     */
    private static String requireNonBlank(String value, String name) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(name + " must be non-blank");
        }
        return value;
    }
}
